# Generated by Django 4.2.1 on 2023-06-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
