# Generated by Django 4.2.1 on 2023-07-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('is_blocked', models.BooleanField(default=False)),
            ],
        ),
    ]
