# Generated by Django 4.2.1 on 2023-06-24 00:40

import apps.exchange.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to=apps.exchange.models.upload_to)),
                ('current_price', models.DecimalField(decimal_places=8, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='FiatCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to=apps.exchange.models.upload_to)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('P', 'В процессе'), ('C', 'Завершена'), ('A', 'Отменена')], default='P', max_length=1)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.cryptocurrency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.fiatcurrency')),
            ],
        ),
    ]
