# Generated by Django 4.2.1 on 2023-06-29 00:50

import apps.exchange.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to=apps.exchange.models.upload_to)),
                ('current_price_usd', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('current_price_pln', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('current_price_rub', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('current_price_uah', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('reception_address', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Криптовалюта',
                'verbose_name_plural': 'Криптовалюты',
            },
        ),
        migrations.CreateModel(
            name='FiatCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to=apps.exchange.models.upload_to)),
                ('current_price_usd', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('reception_address', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Фиат',
                'verbose_name_plural': 'Фиатные валюты',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('unique_transaction_number', models.CharField(max_length=40, unique=True)),
                ('selling_currency', models.CharField(max_length=100)),
                ('selling_amount', models.DecimalField(decimal_places=10, max_digits=20)),
                ('buying_currency', models.CharField(max_length=100)),
                ('buying_amount', models.DecimalField(decimal_places=10, max_digits=20)),
                ('user_reception_address', models.CharField(max_length=255)),
                ('recipient_name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Waiting', 'Ожидает оплаты'), ('Cancel', 'Отменена'), ('UserPaid', 'Оплачена пользователем'), ('Finish', 'Завершена')], default='Waiting', max_length=10)),
                ('eception_address', models.CharField(max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
    ]
