# Generated by Django 4.2.1 on 2023-06-29 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='eception_address',
            new_name='reception_address',
        ),
    ]
