# Generated by Django 4.2.1 on 2023-06-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_options_alter_review_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(max_length=50, verbose_name='Комментарий'),
        ),
    ]
